-- Create table for index rebalancing proposals
CREATE TABLE IF NOT EXISTS index_proposals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  index_id TEXT NOT NULL,
  payload JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Optional index to read recent proposals quickly
CREATE INDEX IF NOT EXISTS idx_index_proposals_created_at ON index_proposals (created_at DESC);
