-- Create table for AI Analyst summaries and metadata
CREATE TABLE IF NOT EXISTS ai_summaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id TEXT NOT NULL,
  summary TEXT,
  embeddings JSONB,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_summaries_doc_id ON ai_summaries (doc_id);
