-- Recreate constituents table for KAXCAP to match app expectations
-- Safe to re-run: drops then creates with required columns and indexes

BEGIN;

DROP TABLE IF EXISTS public.index_constituents_kaxcap CASCADE;

CREATE TABLE public.index_constituents_kaxcap (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticker TEXT NULL,
  isin TEXT NULL,
  name TEXT NULL,
  price DOUBLE PRECISION NULL,
  shares DOUBLE PRECISION NULL,
  mcap DOUBLE PRECISION NULL,
  weight DOUBLE PRECISION NULL,          -- current or raw weight (fraction or %)
  capped_weight DOUBLE PRECISION NULL,   -- current capped weight (fraction or %)
  delta_pct DOUBLE PRECISION NULL,       -- proposed - current (fraction or %)
  avg_daily_volume DOUBLE PRECISION NULL,
  as_of TIMESTAMPTZ NULL,
  source TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Fast lookup for latest snapshot
CREATE INDEX IF NOT EXISTS idx_kaxcap_as_of ON public.index_constituents_kaxcap(as_of DESC);
-- Useful for daily ordering
CREATE INDEX IF NOT EXISTS idx_kaxcap_capped_weight ON public.index_constituents_kaxcap(capped_weight DESC);

COMMIT;
