-- Recreate constituents table for HELXCAP to match app expectations
-- Safe to re-run: drops then creates with required columns and indexes

BEGIN;

DROP TABLE IF EXISTS public.index_constituents_helxcap CASCADE;

CREATE TABLE public.index_constituents_helxcap (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticker TEXT NULL,
  isin TEXT NULL,
  name TEXT NULL,
  price DOUBLE PRECISION NULL,
  shares DOUBLE PRECISION NULL,
  mcap DOUBLE PRECISION NULL,
  weight DOUBLE PRECISION NULL,
  capped_weight DOUBLE PRECISION NULL,
  delta_pct DOUBLE PRECISION NULL,
  avg_daily_volume DOUBLE PRECISION NULL,
  as_of TIMESTAMPTZ NULL,
  source TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_helxcap_as_of ON public.index_constituents_helxcap(as_of DESC);
CREATE INDEX IF NOT EXISTS idx_helxcap_capped_weight ON public.index_constituents_helxcap(capped_weight DESC);

COMMIT;
