-- Recreate quarterly table for HELXCAP
-- Safe to re-run: drops then creates with required columns and indexes

BEGIN;

DROP TABLE IF EXISTS public.index_quarterly_helxcap CASCADE;

CREATE TABLE public.index_quarterly_helxcap (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticker TEXT NULL,
  isin TEXT NULL,
  name TEXT NULL,
  price DOUBLE PRECISION NULL,
  shares DOUBLE PRECISION NULL,
  shares_capped DOUBLE PRECISION NULL,
  mcap_uncapped DOUBLE PRECISION NULL,
  mcap_capped DOUBLE PRECISION NULL,
  curr_weight_uncapped DOUBLE PRECISION NULL,
  curr_weight_capped DOUBLE PRECISION NULL,
  weight DOUBLE PRECISION NULL,
  capped_weight DOUBLE PRECISION NULL,
  delta_pct DOUBLE PRECISION NULL,
  delta_ccy DOUBLE PRECISION NULL,
  delta_vol DOUBLE PRECISION NULL,
  days_to_cover DOUBLE PRECISION NULL,
  avg_vol_30d DOUBLE PRECISION NULL,
  avg_vol_30d_millions DOUBLE PRECISION NULL,
  as_of TIMESTAMPTZ NULL,
  source TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_q_helxcap_as_of ON public.index_quarterly_helxcap(as_of DESC);
CREATE INDEX IF NOT EXISTS idx_q_helxcap_mcap_uncapped ON public.index_quarterly_helxcap(mcap_uncapped DESC);

COMMIT;
